analytics: {}
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.686382
  lightness: 0.42684
  rhythmicContrast: 0.089321
  saturation: 0.613634
cta: {}
layout_spectrum: 0.896959
name: NicholasJamesMarshall
opengraph: {}
purpose: {}
typography_spectrum: 0.471284
